name: Upload Conda Package to PyPI when a Release is Created

on:
  release:
    types: [created]

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false


    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.9 # Or your desired Python version
        channels: conda-forge,defaults

    - name: Install build tools
      shell: bash -l {0}
      run: |
        conda install conda-build anaconda-client -y

    - name: Build Conda package
      shell: bash -l {0}
      run: |
        conda build python/conda-recipe/

    - name: Upload to Anaconda.org
      uses: uibcdf/action-build-and-upload-conda-packages@v1 # Or openalea/action-build-publish-anaconda@v1
      with:
        anaconda-token: ${{ secrets.ANACONDA_TOKEN }}
        package-path: ~/miniconda/conda-bld/noarch/ # Adjust path as needed         