name: Upload Conda Package to PyPI when a Release is Created

on:
  release:
    types: [created]

jobs:
  conda_deployment:
    name: Conda deployment
    runs-on: ubuntu-latest
    environment:
      name: anaconda
      url: https://anaconda.org/ooi
    permissions:
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.11
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true

      - name: Install build tools
        shell: bash -l {0}
        run: |
          conda install conda-build anaconda-client -y


      - name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@v2.0.0
        with:
          meta_yaml_dir: python/conda-recipe/ # Path to meta.yaml directory
          user: ooi # Replace with your Anaconda username (or an Anaconda organization username)
          token: ${{ secrets.ANACONDA_TOKEN }} # Replace with the name of your Anaconda Token secret
          platform_linux-64: true
          platform_osx-64: true
          platform_win-64: true     